language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: CLMTsLvTH+IzlOO7gEr2lYXWGsW8tRgpaVZam2lFcpnMLqHDo6mt3slWAX2y2kvIlO5K+b5FL0DK9V4SQ1gJ+52qNtCUY/4//cQ98c+HBpyJIVq+qS6CXPxTZ1abRIwfewZQ7u1JsLMRpefOhqJIrchjHhkfYR9ascYKedk3d9E=
  # SONATYPE_PASSWORD
  - secure: AYivr/CkeQPq8ZuMi0ydsRE7/1m9mRbEBYDL0/5pknyuj3+Vi3D2rL/6a3N9mPHhtfKZnJd0348BAqQmEkqdfuMlMq02LXxTqoYe8Swa3G3Npks+rMAPfDeS9CZLJShmTs1Vtmn+r3yU70LE7ujwj5DBBGl8nRCfmdiuOMBOONo=
  # GPG_PASSPHRASE
  - secure: bks92T/+w2kQkLLz+3KQBy71hhft+8nMoOAtJKUPJOd8K/5kIq5PyBK6cBOA7jyvBlDibbOmOwiG7vJw5EtOK7+IU9IQNU00y1oYVaUOG+hAF4Aa3gW1a1jNKRDY72m9QThSpEJq0y9sHPf8TAcL3/DdSgtRKu5VlHU2IGff844=
  # GPG_KEYID
  - secure: g4zWk59ns0vWDY8u+a4NMoExy593k89ZSsqXb497+4b+HqSOyGi6kNAT+r4epEyoTcYclvdV1IXGx9NhrkThLcGCv/mAcQw7GWzzKs6slmj0SE/UIZY86KyrDBOBEl2yz66ri1ZOJy2gQBf0S0vkmV6H7ENMl1bXcDbiznR4X3A=
  # GPG_KEY
  - secure: ePCh4B8IzYS7LUtdGNlPetSonFdEa1cxNxj1MPZVewi2ijAaKjp1sOriDr2chRJ30N3a8rIDplVP3mx4QgiQ1gFT+zT0NLxC/fhSJPsvmHuZr0f2fpq3ZqHXL+Mf9LQf6yWcW3KojzsjhEPNlhD9PwgAmTlb7qdQXWi9OmG4IwU=
